//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PdfCreatorForExcel.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PdfCreatorForExcel.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attention, le code permanent n&apos;a pas été trouvé!.
        /// </summary>
        internal static string CreatePdf_CodePermanentEmpty_MessageBoxText {
            get {
                return ResourceManager.GetString("CreatePdf_CodePermanentEmpty_MessageBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Une erreur est survenu lors de la sauvegarde du pdf :(
        ///Erreur:.
        /// </summary>
        internal static string CreatePdf_SavePdfDocument_Exception_MessageBoxText {
            get {
                return ResourceManager.GetString("CreatePdf_SavePdfDocument_Exception_MessageBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez choisir un fichier template.
        /// </summary>
        internal static string LoadPdf_CopyTemplate_ArgumentNullException_MessageBoxText {
            get {
                return ResourceManager.GetString("LoadPdf_CopyTemplate_ArgumentNullException_MessageBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dossier du template non-trouvé.
        /// </summary>
        internal static string LoadPdf_CopyTemplate_DirectoryNotFoundException_MessageBoxText {
            get {
                return ResourceManager.GetString("LoadPdf_CopyTemplate_DirectoryNotFoundException_MessageBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur inconnue! Wow bravo champion ;)
        ///Erreur :.
        /// </summary>
        internal static string LoadPdf_CopyTemplate_Exception_MessageBoxText {
            get {
                return ResourceManager.GetString("LoadPdf_CopyTemplate_Exception_MessageBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fichier du template non-trouvé.
        /// </summary>
        internal static string LoadPdf_CopyTemplate_FileNotFoundException_MessageBoxText {
            get {
                return ResourceManager.GetString("LoadPdf_CopyTemplate_FileNotFoundException_MessageBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tu as probablement ouvert le fichier pdf sur lequel le programme tente d&apos;écrire!.
        /// </summary>
        internal static string LoadPdf_CopyTemplate_IOException_MessageBoxText {
            get {
                return ResourceManager.GetString("LoadPdf_CopyTemplate_IOException_MessageBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous n&apos;êtes pas autorisé à accèder à ce fichier.
        /// </summary>
        internal static string LoadPdf_CopyTemplate_UnauthorizedAccessException_MessageBoxText {
            get {
                return ResourceManager.GetString("LoadPdf_CopyTemplate_UnauthorizedAccessException_MessageBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Une erreur avec PdfSharp est survenue. Voir ThisAddIn.cs ligne 116
        ///Erreur :.
        /// </summary>
        internal static string LoadPdf_OpenTemplate_Exception_MessageBoxText {
            get {
                return ResourceManager.GetString("LoadPdf_OpenTemplate_Exception_MessageBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pdf_icon_2 {
            get {
                object obj = ResourceManager.GetObject("pdf_icon_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pdf créé!.
        /// </summary>
        internal static string PdfCreated {
            get {
                return ResourceManager.GetString("PdfCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap settings {
            get {
                object obj = ResourceManager.GetObject("settings", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon settings1 {
            get {
                object obj = ResourceManager.GetObject("settings1", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
